
steps:

# Build images
  - name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/elasticsearch5:5.2.0'
      - '5.2.0'
  - name: gcr.io/cloud-builders/docker
    args:
      - 'build'
      - '--tag=gcr.io/$PROJECT_ID/elasticsearch2:2.4.4'
      - '2.4.4'

# Run tests

# Add alias tags
  - name: gcr.io/cloud-builders/retagger
    args:
      - 'gcr.io/$PROJECT_ID/elasticsearch5:5.2.0'
      - 'gcr.io/$PROJECT_ID/elasticsearch5:latest'
  - name: gcr.io/cloud-builders/retagger
    args:
      - 'gcr.io/$PROJECT_ID/elasticsearch2:2.4.4'
      - 'gcr.io/$PROJECT_ID/elasticsearch2:latest'

images:
  - 'gcr.io/$PROJECT_ID/elasticsearch5:5.2.0'
  - 'gcr.io/$PROJECT_ID/elasticsearch5:latest'
  - 'gcr.io/$PROJECT_ID/elasticsearch2:2.4.4'
  - 'gcr.io/$PROJECT_ID/elasticsearch2:latest'
